import type { LocationType } from './location.constants'

/**
 * The Thana / District master collection the business supplied.
 *
 * This is a *seed*, not the source of truth — the collection in MongoDB is.
 * The distinction matters: an Admin who corrects a row here does not have it
 * overwritten on the next deploy, because the seeder only ever inserts pairs
 * that are absent. Nothing in this file is read at request time.
 *
 * It exists because a location master with nothing in it classifies nothing,
 * and asking somebody to type six hundred thanas into a form before the
 * feature does anything is not a reasonable first run.
 *
 * Each entry is one district, one location type, and the thanas that carry it.
 * A district appears more than once where its thanas are not all the same type
 * — Gazipur has an OSD-Metro group and an OSD-Thana group — which is the shape
 * the source list has.
 *
 * Where the source list gave a second name in brackets or after a slash
 * ("Shariatpur Sadar (Palong)", "Noakhali Sadar / Sudharam"), both names are
 * seeded as rows of the same type. They are the same place under two names
 * that both turn up on paperwork, and a resolver that only knew one of them
 * would leave half of them unresolved.
 */
export interface SeedGroup {
  district: string
  locationType: LocationType
  thanas: readonly string[]
}

const ISD: LocationType = 'ISD'
const OSD_THANA: LocationType = 'OSD-Thana'
const OSD_METRO: LocationType = 'OSD-Metro'

export const LOCATION_SEED: readonly SeedGroup[] = [
  // --- Dhaka division ------------------------------------------------------
  {
    district: 'Dhaka',
    locationType: OSD_THANA,
    thanas: ['Dhamrai', 'Dohar', 'Keraniganj', 'Nawabganj', 'Savar'],
  },
  {
    /**
     * Dhaka Metropolitan Police. The only ISD block in the list: these are the
     * thanas inside the city the operation delivers into directly.
     */
    district: 'Dhaka',
    locationType: ISD,
    thanas: [
      'Adabor',
      'Badda',
      'Banani',
      'Bangshal',
      'Bimanbandar',
      'Cantonment',
      'Chawkbazar',
      'Dakshinkhan',
      'Darus Salam',
      'Demra',
      'Dhanmondi',
      'Gandaria',
      'Gulshan',
      'Hazaribagh',
      'Jatrabari',
      'Kafrul',
      'Kalabagan',
      'Kamrangirchar',
      'Khilgaon',
      'Khilkhet',
      'Kadamtali',
      'Kotwali',
      'Lalbagh',
      'Mirpur Model',
      'Mohammadpur',
      'Motijheel',
      'Mugda',
      'New Market',
      'Pallabi',
      'Paltan',
      'Ramna Model',
      'Rampura',
      'Rupnagar',
      'Sabujbagh',
      'Shah Ali',
      'Shahbagh',
      'Shahjahanpur',
      'Sutrapur',
      'Shyampur',
      'Sher-e-Bangla Nagar',
      'Tejgaon Industrial Area',
      'Tejgaon',
      'Turag',
      'Uttarkhan',
      'Bhashantek',
      'Vatara',
      'Wari',
    ],
  },
  { district: 'Gazipur', locationType: OSD_METRO, thanas: ['Gazipur Sadar'] },
  {
    district: 'Gazipur',
    locationType: OSD_THANA,
    thanas: ['Kaliganj', 'Kaliakair', 'Kapasia', 'Sreepur'],
  },
  { district: 'Narayanganj', locationType: OSD_METRO, thanas: ['Narayanganj Sadar'] },
  {
    district: 'Narayanganj',
    locationType: OSD_THANA,
    thanas: ['Araihazar', 'Bandar', 'Rupganj', 'Sonargaon'],
  },
  { district: 'Tangail', locationType: OSD_METRO, thanas: ['Tangail Sadar'] },
  {
    district: 'Tangail',
    locationType: OSD_THANA,
    thanas: [
      'Basail',
      'Bhuapur',
      'Delduar',
      'Ghatail',
      'Gopalpur',
      'Kalihati',
      'Madhupur',
      'Mirzapur',
      'Nagarpur',
      'Sakhipur',
      'Dhanbari',
    ],
  },
  { district: 'Manikganj', locationType: OSD_METRO, thanas: ['Manikganj Sadar'] },
  {
    district: 'Manikganj',
    locationType: OSD_THANA,
    thanas: ['Daulatpur', 'Ghior', 'Harirampur', 'Saturia', 'Shibalaya', 'Singair'],
  },
  { district: 'Munshiganj', locationType: OSD_METRO, thanas: ['Munshiganj Sadar'] },
  {
    district: 'Munshiganj',
    locationType: OSD_THANA,
    thanas: ['Gazaria', 'Lauhajang', 'Sreenagar', 'Sirajdikhan', 'Tongibari'],
  },
  { district: 'Narsingdi', locationType: OSD_METRO, thanas: ['Narsingdi Sadar'] },
  {
    district: 'Narsingdi',
    locationType: OSD_THANA,
    thanas: ['Belabo', 'Monohardi', 'Palash', 'Raipura', 'Shibpur'],
  },
  { district: 'Rajbari', locationType: OSD_METRO, thanas: ['Rajbari Sadar'] },
  {
    district: 'Rajbari',
    locationType: OSD_THANA,
    thanas: ['Baliakandi', 'Goalandaghat', 'Pangsha', 'Kalukhali'],
  },
  { district: 'Faridpur', locationType: OSD_METRO, thanas: ['Faridpur Sadar'] },
  {
    district: 'Faridpur',
    locationType: OSD_THANA,
    thanas: [
      'Alfadanga',
      'Boalmari',
      'Bhanga',
      'Charbhadrasan',
      'Madhukhali',
      'Nagarkanda',
      'Sadarpur',
      'Saltha',
    ],
  },
  { district: 'Gopalganj', locationType: OSD_METRO, thanas: ['Gopalganj Sadar'] },
  {
    district: 'Gopalganj',
    locationType: OSD_THANA,
    thanas: ['Kashiani', 'Kotalipara', 'Muksudpur', 'Tungipara'],
  },
  { district: 'Madaripur', locationType: OSD_METRO, thanas: ['Madaripur Sadar'] },
  {
    district: 'Madaripur',
    locationType: OSD_THANA,
    thanas: ['Kalkini', 'Rajoir', 'Shibchar', 'Dasar'],
  },
  {
    district: 'Shariatpur',
    locationType: OSD_METRO,
    thanas: ['Shariatpur Sadar', 'Palong'],
  },
  {
    district: 'Shariatpur',
    locationType: OSD_THANA,
    thanas: ['Bhedarganj', 'Damudya', 'Gosairhat', 'Zajira', 'Naria'],
  },
  { district: 'Kishoreganj', locationType: OSD_METRO, thanas: ['Kishoreganj Sadar'] },
  {
    district: 'Kishoreganj',
    locationType: OSD_THANA,
    thanas: [
      'Bajitpur',
      'Bhairab',
      'Hossainpur',
      'Itna',
      'Karimganj',
      'Katiadi',
      'Kuliarchar',
      'Mithamain',
      'Nikli',
      'Pakundia',
      'Tarail',
      'Austagram',
    ],
  },

  // --- Chattogram division -------------------------------------------------
  {
    district: 'Chattogram',
    locationType: OSD_THANA,
    thanas: [
      'Anwara',
      'Banshkhali',
      'Boalkhali',
      'Chandanaish',
      'Fatikchhari',
      'Hathazari',
      'Lohagara',
      'Mirsharai',
      'Patiya',
      'Rangunia',
      'Raozan',
      'Sandwip',
      'Satkania',
      'Sitakunda',
      'Karnaphuli',
    ],
  },
  {
    /** Chattogram Metropolitan Police. */
    district: 'Chattogram',
    locationType: OSD_METRO,
    thanas: [
      'Kotwali',
      'Chandgaon',
      'Panchlaish',
      'Double Mooring',
      'Pahartali',
      'Bandar',
      'Bayezid Bostami',
      'Halishahar',
      'Patenga',
      'Bakalia',
      'Akbar Shah',
      'Sadarghat',
      'EPZ',
      'Chawkbazar',
      'Khulshi',
    ],
  },
  { district: "Cox's Bazar", locationType: OSD_METRO, thanas: ["Cox's Bazar Sadar"] },
  {
    district: "Cox's Bazar",
    locationType: OSD_THANA,
    thanas: ['Chakaria', 'Kutubdia', 'Maheshkhali', 'Ramu', 'Teknaf', 'Ukhia', 'Pekua'],
  },
  {
    district: 'Cumilla',
    locationType: OSD_METRO,
    thanas: ['Cumilla Sadar', 'Sadar Dakshin', 'South Sadar'],
  },
  {
    district: 'Cumilla',
    locationType: OSD_THANA,
    thanas: [
      'Barura',
      'Brahmanpara',
      'Chandina',
      'Chauddagram',
      'Daudkandi',
      'Debidwar',
      'Homna',
      'Laksam',
      'Muradnagar',
      'Nangalkot',
      'Meghna',
      'Monohorgonj',
      'Titas',
      'Burichang',
      'Lalmai',
    ],
  },
  { district: 'Brahmanbaria', locationType: OSD_METRO, thanas: ['Brahmanbaria Sadar'] },
  {
    district: 'Brahmanbaria',
    locationType: OSD_THANA,
    thanas: [
      'Ashuganj',
      'Bancharampur',
      'Bijoynagar',
      'Kasba',
      'Nabinagar',
      'Nasirnagar',
      'Sarail',
      'Akhaura',
    ],
  },
  { district: 'Chandpur', locationType: OSD_METRO, thanas: ['Chandpur Sadar'] },
  {
    district: 'Chandpur',
    locationType: OSD_THANA,
    thanas: [
      'Faridganj',
      'Haimchar',
      'Hajiganj',
      'Kachua',
      'Matlab Dakshin',
      'Matlab Uttar',
      'Shahrasti',
    ],
  },
  { district: 'Lakshmipur', locationType: OSD_METRO, thanas: ['Lakshmipur Sadar'] },
  {
    district: 'Lakshmipur',
    locationType: OSD_THANA,
    thanas: ['Kamalnagar', 'Ramganj', 'Raipur', 'Ramgati'],
  },
  {
    district: 'Noakhali',
    locationType: OSD_METRO,
    thanas: ['Noakhali Sadar', 'Sudharam'],
  },
  {
    district: 'Noakhali',
    locationType: OSD_THANA,
    thanas: [
      'Begumganj',
      'Chatkhil',
      'Companiganj',
      'Hatiya',
      'Kabirhat',
      'Senbagh',
      'Sonaimuri',
      'Subarnachar',
    ],
  },
  { district: 'Feni', locationType: OSD_METRO, thanas: ['Feni Sadar'] },
  {
    district: 'Feni',
    locationType: OSD_THANA,
    thanas: ['Chhagalnaiya', 'Daganbhuiyan', 'Fulgazi', 'Parshuram', 'Sonagazi'],
  },
  { district: 'Khagrachhari', locationType: OSD_METRO, thanas: ['Khagrachhari Sadar'] },
  {
    district: 'Khagrachhari',
    locationType: OSD_THANA,
    thanas: [
      'Dighinala',
      'Lakshmichhari',
      'Matiranga',
      'Manikchhari',
      'Panchhari',
      'Ramgarh',
      'Mahalchhari',
      'Guimara',
    ],
  },
  { district: 'Rangamati', locationType: OSD_METRO, thanas: ['Rangamati Sadar'] },
  {
    district: 'Rangamati',
    locationType: OSD_THANA,
    thanas: [
      'Baghaichhari',
      'Barkal',
      'Bilaichhari',
      'Juraichhari',
      'Kaptai',
      'Kawkhali',
      'Langadu',
      'Naniarchar',
      'Rajasthali',
    ],
  },
  { district: 'Bandarban', locationType: OSD_METRO, thanas: ['Bandarban Sadar'] },
  {
    district: 'Bandarban',
    locationType: OSD_THANA,
    thanas: ['Alikadam', 'Lama', 'Naikhongchhari', 'Ruma', 'Rowangchhari', 'Thanchi'],
  },

  // --- Rajshahi division ---------------------------------------------------
  {
    district: 'Rajshahi',
    locationType: OSD_THANA,
    thanas: [
      'Bagmara',
      'Bagha',
      'Charghat',
      'Durgapur',
      'Godagari',
      'Mohanpur',
      'Paba',
      'Puthia',
      'Tanore',
      // Rajshahi Metropolitan Police, outer thanas.
      'Damkura',
      'Karnahar',
      'Belpukur',
      'Katakhali',
      'Boalia',
    ],
  },
  {
    /** Rajshahi Metropolitan Police, city thanas. */
    district: 'Rajshahi',
    locationType: OSD_METRO,
    thanas: ['Rajpara', 'Chandrima', 'Motihar', 'Shah Makhdum', 'Airport', 'Kashiadanga'],
  },
  { district: 'Natore', locationType: OSD_METRO, thanas: ['Natore Sadar'] },
  {
    district: 'Natore',
    locationType: OSD_THANA,
    thanas: ['Bagatipara', 'Baraigram', 'Gurudaspur', 'Lalpur', 'Singra', 'Naldanga'],
  },
  { district: 'Naogaon', locationType: OSD_METRO, thanas: ['Naogaon Sadar'] },
  {
    district: 'Naogaon',
    locationType: OSD_THANA,
    thanas: [
      'Atrai',
      'Badalgachhi',
      'Dhamoirhat',
      'Mahadebpur',
      'Manda',
      'Niamatpur',
      'Patnitala',
      'Porsha',
      'Raninagar',
      'Sapahar',
    ],
  },
  { district: 'Chapainawabganj', locationType: OSD_METRO, thanas: ['Nawabganj Sadar'] },
  {
    district: 'Chapainawabganj',
    locationType: OSD_THANA,
    thanas: ['Bholahat', 'Gomastapur', 'Nachole', 'Shibganj'],
  },
  { district: 'Pabna', locationType: OSD_METRO, thanas: ['Pabna Sadar'] },
  {
    district: 'Pabna',
    locationType: OSD_THANA,
    thanas: [
      'Atgharia',
      'Bera',
      'Bhangura',
      'Chatmohar',
      'Faridpur',
      'Ishwardi',
      'Santhia',
      'Sujanagar',
    ],
  },
  { district: 'Sirajganj', locationType: OSD_METRO, thanas: ['Sirajganj Sadar'] },
  {
    district: 'Sirajganj',
    locationType: OSD_THANA,
    thanas: [
      'Belkuchi',
      'Chauhali',
      'Kamarkhanda',
      'Kazipur',
      'Raiganj',
      'Shahjadpur',
      'Tarash',
      'Ullapara',
    ],
  },
  { district: 'Bogura', locationType: OSD_METRO, thanas: ['Bogura Sadar'] },
  {
    district: 'Bogura',
    locationType: OSD_THANA,
    thanas: [
      'Adamdighi',
      'Dupchanchia',
      'Dhunat',
      'Gabtali',
      'Kahaloo',
      'Nandigram',
      'Sariakandi',
      'Shajahanpur',
      'Shibganj',
      'Sherpur',
      'Sonatala',
    ],
  },
  { district: 'Joypurhat', locationType: OSD_METRO, thanas: ['Joypurhat Sadar'] },
  {
    district: 'Joypurhat',
    locationType: OSD_THANA,
    thanas: ['Akkelpur', 'Kalai', 'Khetlal', 'Panchbibi'],
  },

  // --- Khulna division -----------------------------------------------------
  {
    district: 'Khulna',
    locationType: OSD_THANA,
    thanas: [
      'Batiaghata',
      'Dacope',
      'Dumuria',
      'Dighalia',
      'Koyra',
      'Paikgachha',
      'Phultala',
      'Rupsa',
      'Terokhada',
      // Khulna Metropolitan Police, outer thanas.
      'Sonadanga',
      'Khalishpur',
      'Daulatpur',
      'Khan Jahan Ali',
      'Labanchara',
      'Harintana',
      'Aranghata',
    ],
  },
  {
    district: 'Khulna',
    locationType: OSD_METRO,
    thanas: ['Khulna Sadar', 'Kotwali'],
  },
  { district: 'Bagerhat', locationType: OSD_METRO, thanas: ['Bagerhat Sadar'] },
  {
    district: 'Bagerhat',
    locationType: OSD_THANA,
    thanas: [
      'Chitalmari',
      'Fakirhat',
      'Kachua',
      'Mongla',
      'Morrelganj',
      'Rampal',
      'Sarankhola',
      'Mollahat',
    ],
  },
  { district: 'Satkhira', locationType: OSD_METRO, thanas: ['Satkhira Sadar'] },
  {
    district: 'Satkhira',
    locationType: OSD_THANA,
    thanas: ['Assasuni', 'Debhata', 'Kaliganj', 'Kalaroa', 'Shyamnagar', 'Tala'],
  },
  { district: 'Jashore', locationType: OSD_METRO, thanas: ['Jashore Sadar'] },
  {
    district: 'Jashore',
    locationType: OSD_THANA,
    thanas: [
      'Abhaynagar',
      'Bagherpara',
      'Chaugachha',
      'Jhikargachha',
      'Keshabpur',
      'Manirampur',
      'Sharsha',
    ],
  },
  { district: 'Magura', locationType: OSD_METRO, thanas: ['Magura Sadar'] },
  {
    district: 'Magura',
    locationType: OSD_THANA,
    thanas: ['Mohammadpur', 'Shalikha', 'Sreepur'],
  },
  { district: 'Jhenaidah', locationType: OSD_METRO, thanas: ['Jhenaidah Sadar'] },
  {
    district: 'Jhenaidah',
    locationType: OSD_THANA,
    thanas: ['Harinakunda', 'Kaliganj', 'Kotchandpur', 'Moheshpur', 'Shailkupa'],
  },
  { district: 'Narail', locationType: OSD_METRO, thanas: ['Narail Sadar'] },
  { district: 'Narail', locationType: OSD_THANA, thanas: ['Kalia', 'Lohagara'] },
  { district: 'Chuadanga', locationType: OSD_METRO, thanas: ['Chuadanga Sadar'] },
  {
    district: 'Chuadanga',
    locationType: OSD_THANA,
    thanas: ['Alamdanga', 'Damurhuda', 'Jibannagar'],
  },
  { district: 'Meherpur', locationType: OSD_METRO, thanas: ['Meherpur Sadar'] },
  { district: 'Meherpur', locationType: OSD_THANA, thanas: ['Gangni', 'Mujibnagar'] },
  { district: 'Kushtia', locationType: OSD_METRO, thanas: ['Kushtia Sadar'] },
  {
    district: 'Kushtia',
    locationType: OSD_THANA,
    thanas: ['Bheramara', 'Daulatpur', 'Khoksa', 'Kumarkhali', 'Mirpur'],
  },

  // --- Barishal division ---------------------------------------------------
  {
    district: 'Barishal',
    locationType: OSD_METRO,
    thanas: ['Barishal Sadar', 'Kotwali Model'],
  },
  {
    district: 'Barishal',
    locationType: OSD_THANA,
    thanas: [
      'Agailjhara',
      'Babuganj',
      'Bakerganj',
      'Banaripara',
      'Gournadi',
      'Hizla',
      'Mehendiganj',
      'Muladi',
      'Wazirpur',
      // Barishal Metropolitan Police, outer thanas.
      'Airport',
      'Kawnia',
      'Bandar',
    ],
  },
  { district: 'Bhola', locationType: OSD_METRO, thanas: ['Bhola Sadar'] },
  {
    district: 'Bhola',
    locationType: OSD_THANA,
    thanas: ['Borhanuddin', 'Charfasson', 'Daulatkhan', 'Lalmohan', 'Manpura', 'Tazumuddin'],
  },
  { district: 'Patuakhali', locationType: OSD_METRO, thanas: ['Patuakhali Sadar'] },
  {
    district: 'Patuakhali',
    locationType: OSD_THANA,
    thanas: ['Bauphal', 'Dashmina', 'Dumki', 'Galachipa', 'Kalapara', 'Mirzaganj', 'Rangabali'],
  },
  { district: 'Pirojpur', locationType: OSD_METRO, thanas: ['Pirojpur Sadar'] },
  {
    district: 'Pirojpur',
    locationType: OSD_THANA,
    thanas: [
      'Bhandaria',
      'Kawkhali',
      'Mathbaria',
      'Nazirpur',
      'Nesarabad',
      'Swarupkati',
      'Indurkani',
    ],
  },
  { district: 'Barguna', locationType: OSD_METRO, thanas: ['Barguna Sadar'] },
  {
    district: 'Barguna',
    locationType: OSD_THANA,
    thanas: ['Amtali', 'Bamna', 'Betagi', 'Patharghata', 'Taltali'],
  },
  { district: 'Jhalokati', locationType: OSD_METRO, thanas: ['Jhalokati Sadar'] },
  {
    district: 'Jhalokati',
    locationType: OSD_THANA,
    thanas: ['Kathalia', 'Nalchity', 'Rajapur'],
  },

  // --- Sylhet division -----------------------------------------------------
  {
    district: 'Sylhet',
    locationType: OSD_METRO,
    thanas: ['Sylhet Sadar', 'Kotwali Model'],
  },
  {
    district: 'Sylhet',
    locationType: OSD_THANA,
    thanas: [
      'Balaganj',
      'Beanibazar',
      'Bishwanath',
      'Companiganj',
      'Fenchuganj',
      'Golapganj',
      'Gowainghat',
      'Jaintiapur',
      'Kanaighat',
      'Osmani Nagar',
      'Dakshin Surma',
      'Zakiganj',
      // Sylhet Metropolitan Police, outer thanas.
      'Jalalabad',
      'Airport',
      'South Surma',
      'Moglabazar',
      'Shahporan',
    ],
  },
  { district: 'Moulvibazar', locationType: OSD_METRO, thanas: ['Moulvibazar Sadar'] },
  {
    district: 'Moulvibazar',
    locationType: OSD_THANA,
    thanas: ['Barlekha', 'Kamalganj', 'Kulaura', 'Rajnagar', 'Sreemangal', 'Juri'],
  },
  { district: 'Habiganj', locationType: OSD_METRO, thanas: ['Habiganj Sadar'] },
  {
    district: 'Habiganj',
    locationType: OSD_THANA,
    thanas: [
      'Ajmiriganj',
      'Bahubal',
      'Baniachong',
      'Chunarughat',
      'Lakhai',
      'Madhabpur',
      'Nabiganj',
      'Shayestaganj',
    ],
  },
  { district: 'Sunamganj', locationType: OSD_METRO, thanas: ['Sunamganj Sadar'] },
  {
    district: 'Sunamganj',
    locationType: OSD_THANA,
    thanas: [
      'Bishwambharpur',
      'Chhatak',
      'Dakshin Sunamganj',
      'Derai',
      'Dowarabazar',
      'Dharampasha',
      'Jagannathpur',
      'Jamalganj',
      'Shalla',
      'Tahirpur',
      'Madhyanagar',
    ],
  },

  // --- Rangpur division ----------------------------------------------------
  { district: 'Rangpur', locationType: OSD_METRO, thanas: ['Rangpur Sadar'] },
  {
    district: 'Rangpur',
    locationType: OSD_THANA,
    thanas: ['Badarganj', 'Gangachara', 'Kaunia', 'Mithapukur', 'Pirganj', 'Pirgachha', 'Taraganj'],
  },
  { district: 'Dinajpur', locationType: OSD_METRO, thanas: ['Dinajpur Sadar'] },
  {
    district: 'Dinajpur',
    locationType: OSD_THANA,
    thanas: [
      'Birganj',
      'Biral',
      'Bochaganj',
      'Chirirbandar',
      'Fulbari',
      'Ghoraghat',
      'Hakimpur',
      'Kaharole',
      'Khansama',
      'Nawabganj',
      'Parbatipur',
      'Birampur',
    ],
  },
  { district: 'Gaibandha', locationType: OSD_METRO, thanas: ['Gaibandha Sadar'] },
  {
    district: 'Gaibandha',
    locationType: OSD_THANA,
    thanas: ['Fulchhari', 'Gobindaganj', 'Palashbari', 'Saghata', 'Sadullapur', 'Sundarganj'],
  },
  { district: 'Kurigram', locationType: OSD_METRO, thanas: ['Kurigram Sadar'] },
  {
    district: 'Kurigram',
    locationType: OSD_THANA,
    thanas: [
      'Bhurungamari',
      'Char Rajibpur',
      'Chilmari',
      'Phulbari',
      'Nageshwari',
      'Rajarhat',
      'Roumari',
      'Ulipur',
    ],
  },
  { district: 'Lalmonirhat', locationType: OSD_METRO, thanas: ['Lalmonirhat Sadar'] },
  {
    district: 'Lalmonirhat',
    locationType: OSD_THANA,
    thanas: ['Aditmari', 'Hatibandha', 'Kaliganj', 'Patgram'],
  },
  { district: 'Nilphamari', locationType: OSD_METRO, thanas: ['Nilphamari Sadar'] },
  {
    district: 'Nilphamari',
    locationType: OSD_THANA,
    thanas: ['Dimla', 'Domar', 'Jaldhaka', 'Kishoreganj', 'Saidpur'],
  },
  { district: 'Panchagarh', locationType: OSD_METRO, thanas: ['Panchagarh Sadar'] },
  {
    district: 'Panchagarh',
    locationType: OSD_THANA,
    thanas: ['Atwari', 'Boda', 'Debiganj', 'Tetulia'],
  },
  { district: 'Thakurgaon', locationType: OSD_METRO, thanas: ['Thakurgaon Sadar'] },
  {
    district: 'Thakurgaon',
    locationType: OSD_THANA,
    thanas: ['Baliadangi', 'Haripur', 'Pirganj', 'Ranisankail'],
  },

  // --- Mymensingh division -------------------------------------------------
  { district: 'Mymensingh', locationType: OSD_METRO, thanas: ['Mymensingh Sadar'] },
  {
    district: 'Mymensingh',
    locationType: OSD_THANA,
    thanas: [
      'Bhaluka',
      'Dhobaura',
      'Fulbaria',
      'Gafargaon',
      'Dakshin Gafargaon',
      'Gauripur',
      'Haluaghat',
      'Ishwarganj',
      'Muktagachha',
      'Nandail',
      'Phulpur',
      'Trishal',
    ],
  },
  { district: 'Jamalpur', locationType: OSD_METRO, thanas: ['Jamalpur Sadar'] },
  {
    district: 'Jamalpur',
    locationType: OSD_THANA,
    thanas: ['Bakshiganj', 'Dewanganj', 'Islampur', 'Madarganj', 'Melandaha', 'Sarishabari'],
  },
  { district: 'Netrokona', locationType: OSD_METRO, thanas: ['Netrokona Sadar'] },
  {
    district: 'Netrokona',
    locationType: OSD_THANA,
    thanas: [
      'Atpara',
      'Barhatta',
      'Durgapur',
      'Khaliajuri',
      'Kalmakanda',
      'Kendua',
      'Madan',
      'Mohanganj',
      'Purbadhala',
    ],
  },
  { district: 'Sherpur', locationType: OSD_METRO, thanas: ['Sherpur Sadar'] },
  {
    district: 'Sherpur',
    locationType: OSD_THANA,
    thanas: ['Nalitabari', 'Nakla', 'Sreebardi', 'Jhenaigati'],
  },

  // --- Gazipur Metropolitan Police -----------------------------------------
  {
    district: 'Gazipur',
    locationType: OSD_METRO,
    thanas: ['Joydebpur', 'Bason', 'Konabari', 'Kashimpur', 'Gacha', 'Pubail'],
  },
  {
    district: 'Gazipur',
    locationType: OSD_THANA,
    thanas: ['Tongi East', 'Tongi West'],
  },
]
